/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Sound */

#ifndef _Included_Sound
#define _Included_Sound
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Sound
 * Method:    initCpp
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_Sound_initCpp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Sound
 * Method:    playCpp
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Sound_playCpp
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
